@BASE_URL = http://localhost:3000/api/v1
@REFRESH_TOKEN="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXNzaW9uSWQiOiI2YTkxNDRkMjhmMTI3MTA0NGQxMjdiOWUiLCJpYXQiOjE3ODc5MDUyMzQsImV4cCI6MTc4ODUxMDAzNCwiYXVkIjoidXNlciIsImlzcyI6ImFkdmFuY2UtbWVybi1hdXRoIn0.hTUWC_d6VrFw3YqDHM5rK2WqlSsWCPgoWjU0UDaeFj4"

### Register
POST {{BASE_URL}}/auth/register
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john.doe@example.com",
    "password": "securepassword",
    "confirmPassword": "securepassword"
}

### Login
POST {{BASE_URL}}/auth/login
Content-Type: application/json

{
    "email": "john.doe@example.com",
    "password": "securepassword"
}

### Refresh Token

GET {{BASE_URL}}/auth/refresh
Cookie: refreshToken= {{REFRESH_TOKEN}}

### Verify Email

POST {{BASE_URL}}/auth/verify/email
Content-Type: application/json

{
    "code":"4695af07910f496a9743a484d"
}
